//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experience_EcommLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reimbursement_Form
    {
        public int Rem_ID { get; set; }
        public string Month { get; set; }
        public string Reimbursement_type { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string Purpose { get; set; }
        public string Mode { get; set; }
        public string km { get; set; }
        public string InvNo { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Attachment { get; set; }
        public string Hotel_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
